/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on Jan 31, 2010, 6:45:45 PM
 */
package ibnums;

import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;

/**
 *
 * @author rickcharon
 */
public class MainForm extends javax.swing.JFrame {

  /** Creates new form MainForm */
  public MainForm() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    IBcodeEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("IBnumsPU").createEntityManager();
    num1TextField = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    num2TextField = new javax.swing.JTextField();
    codeTextField = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("IB Code");
    setLocationByPlatform(true);
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    num1TextField.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    num1TextField.setNextFocusableComponent(num2TextField);

    jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
    jLabel1.setText("num1:");
    jLabel1.setFocusable(false);

    jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
    jLabel2.setText("num2:");
    jLabel2.setFocusable(false);

    num2TextField.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
    num2TextField.setNextFocusableComponent(codeTextField);

    codeTextField.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    codeTextField.setInheritsPopupMenu(true);
    codeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        codeTextFieldFocusGained(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(8, 8, 8)
        .addComponent(num1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel2)
        .addGap(8, 8, 8)
        .addComponent(num2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(57, 57, 57)
        .addComponent(codeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(62, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(num1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1)
            .addComponent(num2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2))
          .addComponent(codeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(32, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void codeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codeTextFieldFocusGained
      //IBcard ibc = new IBcard();
      Integer num1 = Integer.parseInt(num1TextField.getText());
      Object tt = IBcodeEntityManager.createNamedQuery("IBcard.findCodeByNum").setParameter("num", num1).getSingleResult();
      String outp = tt.toString();
      Integer num2 = Integer.parseInt(num2TextField.getText());
      tt = IBcodeEntityManager.createNamedQuery("IBcard.findCodeByNum").setParameter("num", num2).getSingleResult();
      codeTextField.setText(outp + tt.toString());
      Clipboard clipboard = getToolkit().getSystemClipboard();
      StringSelection data = new StringSelection(codeTextField.getText());
      clipboard.setContents(data, data);
    }//GEN-LAST:event_codeTextFieldFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new MainForm().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.persistence.EntityManager IBcodeEntityManager;
  private javax.swing.JTextField codeTextField;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField num1TextField;
  private javax.swing.JTextField num2TextField;
  // End of variables declaration//GEN-END:variables
}
