#!/bin/bash 
# Note: set -v is set -o verbose and set -x is set -o xtrace ; (-vx is equivalent on top line.) Use this to echo all.
# <2014-06-21 Sat 08:50> Run this to git commit the /share/pts project.

echo "Hard linking extra files."
extraFiles=( /share/elisp/ptsprogs.el /share/notes/notes-charts /share/notes/notes-petrasys /share/notes/notes-tradingutils \
    /share/notes/notes-trading /share/notes/notes-trades /share/scripts/gitcommitpts )
extrasDir="/share/pts/extras/"
mainDir="/share/pts"

bName=""

for exfile in "${extraFiles[@]}"
do
    bName=$(basename $exfile)
    fvar="${extrasDir}${bName}"
    if [ -f ${fvar} ]
    then
        rm $fvar
        echo "-> ${fvar} removed".
    else
        echo "-> ${fvar} not found".
    fi
    ln $exfile $fvar
    echo "-> hard linked ${exfile} to ${fvar}"
done
set -x
# ls -l "${extrasDir}"
# set +x
cd $mainDir
git add .
git commit

